import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ['400', '700'], 
});

export const metadata = {
  title: "FCT Flags Submission",
  description: "Generated by Raya Prasetya",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        {children}
        <Toaster richColors/>
      </body>
    </html>
  );
}
